version: "3.9"

# the various services
services:
# api - is our rest api
  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
# db - is the mariadb
  db:
    container_name: db
    image: "mariadb"
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: test
      MARIADB_PASSWORD: test
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: test